### ISSUE TITLE
Insecure connexion

### ISSUE THREAD

**Issue by ReinforcedKnowledge** [Masterjx9/Outlook-Addin-TaskPane-python#2]
Hi!

Thanks a lot for the work that you have done on this project. I tried to run your repo to get a feeling of how this works but I get insecure connexion when I go to `https://localhost:5000`.

Your javascript code works when I put it together in the Script Lab Add-in. It's just that it can't fetch anything from the local server. I was wondering if you have any news regarding this issue.

Below are the information regarding my environment:

Ubuntu 23.10
Python 3.11.6
Libraries are installed from your requirements file
Browser: Brave 1.65.133 Chromium: 124.0.6367.208 (Official Build) (64-bit)

Thank you!

**Comment by Masterjx9** [comment]
Hey @ReinforcedKnowledge - I believe the last update I did some months ago included something to allow dev certs to be added to your windows cert store so that you don't get that error when developing with the addin. However, I don't remember right now haha.

Ok, I remember somewhat now - I believe its this code right here:
`if __name__ == "__main__":
    if os.environ.get("APP_MODE") == "DEV":
        print("Running in DEV mode")
        # Call the function to ensure certificates are installed and valid
        ensure_certificates_are_installed()

        # Assuming the ensure_certificates_are_installed function updates the default paths as needed
        from devcerts.defaults import localhost_certificate_path, localhost_key_path
        ssl_context = (localhost_certificate_path, localhost_key_path)
        
        app.run(debug=True, ssl_context=ssl_context)
    else:
        app.run(debug=True)`

This function here ensure_certificates_are_installed() - should popup something on your windows computer in a grey screen that asks you if you can install the dev certs. Once you hit yes, it should authorize your https connection for local development. **By any chance did you see a popup**? If you didn't you can try just manually installing the dev-certs by using the actual repo from here - https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/office-addin-dev-certs

**Are you running on windows?**

Also you said the browser is the brave browser? But this is an outlook addin, this wouldn't be made for direct use in the web browser (It can be but I don't think I setup this template with that), its used only for outlook as an addin pane. The browser in outlook is usually the edge browser, unless you were able to change your browser for outlook?? 

I am currently about to get ready for work, but I will look for your response later today (PST) or this weekend.

**Comment by ReinforcedKnowledge** [comment]
Hi! Thank you for your very fast reply.

Yes indeed I saw the popup! I'm on Linux but I think you have provided scripts for that as well. I did enter yes and my password to install the certificates and weirdly the server runs on `https`. At least that's what it says on the logs, but when I go to the browser it says insecure connexion.

I have not tried the Add-in yet (the manifest) because I wanted to check the connexion first before going further. But I thought the Add-in was possible to be put on the web version of Outlook as well. Maybe it's not, to be honest it's my first time with Office Add-ins and being on Linux makes it hard to test on Desktop versions of Office products. I should try it on Edge 🤔

It's okay you can reply whenever you feel the right time, good luck with work!

**Comment by Masterjx9** [comment]
It is possible to put on the web in chrome, that is true but because I put in https for local development, the browser will complain about it, as it's meant for outlook directly. I think the reason this had to be put https is because outlook itself wont allow you to test with http directly locally which is annoying. 

Since you did add the dev certs, this should work in outlook as it will use the dev cert to get around this error
<img width="177" alt="image" src="https://github.com/Masterjx9/Outlook-Addin-TaskPane-python/assets/82799287/9bcc969b-c45a-4cad-8c1f-60a51e725874">

**However the dev-certs from microsoft don't work for the actual browser**. There are only two ways I can think to work around the issue if you want an outlook webapp that also works the web for local development testing:

- use ngrok instead of localhost
- you push the app to the cloud so it can have an https

ngrok is probably the best choice but the most annoying as you have to change the manifest file's urls from localhost to whatever ngrok gives you for a url. 

I will update the repo with instructions on how to use ngrok. 
I'll also do some testing on livestream on twitch or on meetup in some days. - https://www.meetup.com/code-network-la/

I'll reply back after work or this weekend with an update. 👍

**Comment by ReinforcedKnowledge** [comment]
Thanks a lot!!!

Using `ngrok` did work for me. I could fetch from my Python backend using the JS on Script Lab.

The task pane doesn't load unfortunately it blocks on the `You are about to visit...`. But I will find a way to bypass that. Or just pay for the lowest tier subscription plan ^^'

Thanks a lot for your replies. I'll will try to attend your livestream / meetup 😄

**Comment by Masterjx9** [comment]
Hey @ReinforcedKnowledge - I was able to test this and it works in the browser directly for me without having to do anything. I haven't messed with the repo in a bit so I had to clone it and test and it worked no problem. 

Once I cloned and cd into the directory I did the following:

- py -m venv .venv (this should be python3 -m venv .venv in linux)
- .venv/scripts/activate (this should be source .venv/bin/activate in linux)
- pip install -r requirements.txt
- python app.py
- Accept the dev certs
- Once the site is running I then went into google chrome and went to https://127.0.0.1:5000/ 
- Allow https unsecure connection as the dev certs are not real certs from a CA (certificate authority) 

![image](https://github.com/Masterjx9/Outlook-Addin-TaskPane-python/assets/82799287/6b347667-ef69-45c4-956f-f9b11d3b371c)

- After that you should see the site

<img width="475" alt="image" src="https://github.com/Masterjx9/Outlook-Addin-TaskPane-python/assets/82799287/d47c8541-0fab-4b98-977d-9e4335010732">
<img width="586" alt="image" src="https://github.com/Masterjx9/Outlook-Addin-TaskPane-python/assets/82799287/2ac92964-8b7b-4ca1-9ce9-7139f73bfdec">

This template is only supported for outlook addins directly however, from this testing, this does prove that the template does work directly on the web which is useful for development and for creating a cross platform web app and outlook app all in one. 

If you are still having issues, I would recommend changing browsers and testing. 

I'll leave this issue open for a day for now 👍
